GNU Radio's LORA Package: gr::lora Namespace Reference
gr::lora Namespace Reference
Classes
class channelizer
<+description of block+>
class channelizer_impl
class controller
class controller_impl
class debugger
class decoder
<+description of block+>
class decoder_impl
Return the DecoderState as string for debugging purposes.
class message_file_sink
<+description of block+>
class message_file_sink_impl
class message_socket_sink
Sink for messages, sent to socket.
class message_socket_sink_impl
Enumerations
enum DecoderState {
DecoderState::DETECT, DecoderState::SYNC, DecoderState::FIND_SFD, DecoderState::PAUSE,
DecoderState::DECODE_HEADER, DecoderState::DECODE_PAYLOAD, DecoderState::STOP
}
DecoderState : Each state the LoRa decoder can be in.
Functions
template<class T >
T clamp (const T d, const T min, const T max)
Clamp given value in the given range.
uint32_t rotl (uint32_t bits, uint32_t count=1u, const uint32_t size=8u)
Rotate the given bits to the left and return the result.
template<typename T >
std::string to_bin (const T v, const uint32_t bitwidth)
Return the v represented in a binary string.
template<typename T >
void print_vector_bin (std::ostream &out, const std::vector< T > &v, const std::string &prefix, const int element_len_bits)
Append the data in a given vector to an output stream with a comma delimiter.
bool check_parity_string (const std::string &word, const bool even=true)
Check whether the parity of the given binary string is even.
bool check_parity (uint64_t word, const bool even=true)
Check whether the parity of the given uint64_t is even.
See https://graphics.stanford.edu/~seander/bithacks.html for more.
uint32_t select_bits (const uint32_t data, const uint8_t *indices, const uint8_t n)
Select the bits in data given by the indices in *indices.
uint8_t bit (const uint8_t v, const uint8_t i)
Select a single bit from the given byte.
uint8_t pack_byte (const uint8_t a, const uint8_t b, const uint8_t c, const uint8_t d, const uint8_t e, const uint8_t f, const uint8_t g, const uint8_t h)
Pack the given 8 bits in a byte with: hgfe dcba
uint8_t pack_nibble (const uint8_t a, const uint8_t b, const uint8_t c, const uint8_t d)
Pack the given 4 bits in a nibble with: dcba
uint8_t hamming_encode_soft (const uint8_t v)
Encode the given word with standard Hamming(7,4) and return a byte with the set parity bits.
static uint8_t hamming_decode_soft_byte (uint8_t v)
Hamming(8,4) decoding by constructing a Syndrome matrix LUT for XORing on parity errors.
template<typename T >
void print_vector (std::ostream &out, const T *v, const std::string &prefix, const int size, const int element_len_bits)
template<typename T >
void print_vector_hex (std::ostream &out, const T *v, const uint32_t size, bool endline)
template<typename T >
void print_interleave_matrix (std::ostream &out, const std::vector< T > &v, const uint32_t sf)
uint32_t dissect_packet (const void **header, uint32_t header_size, const uint8_t *buffer, uint32_t offset)
uint32_t build_packet (uint8_t *buffer, uint32_t offset, const void *header, uint32_t header_size)
Variables
const uint8_t prng_header []
const uint8_t prng_payload []
Enumeration Type Documentation
DecoderState
enum gr::lora::DecoderState strong
DecoderState : Each state the LoRa decoder can be in.
Enumerator
DETECT
SYNC
FIND_SFD
PAUSE
DECODE_HEADER
DECODE_PAYLOAD
STOP
Function Documentation
bit()
uint8_t gr::lora::bit (const uint8_t v, const uint8_t i) inline
Select a single bit from the given byte.
Parameters
v The byte to select from.
i The index to select the bit from starting from the LSB.
Referenced by hamming_decode_soft_byte(), and hamming_encode_soft().
build_packet()
uint32_t gr::lora::build_packet (uint8_t * buffer, uint32_t offset, const void * header, uint32_t header_size) inline
check_parity()
bool gr::lora::check_parity (uint64_t word, const bool even = true) inline
Check whether the parity of the given uint64_t is even.
See https://graphics.stanford.edu/~seander/bithacks.html for more.
Parameters
word The uint64_t to check.
even Check for even (true) or uneven (false) parity.
check_parity_string()
bool gr::lora::check_parity_string (const std::string & word, const bool even = true) inline
Check whether the parity of the given binary string is even.
Parameters
word The string to check.
even Check for even (true) or uneven (false) parity.
clamp()
template<class T > T gr::lora::clamp (const T d, const T min, const T max) inline
Clamp given value in the given range.
Template Parameters
T The type of variable to clamp.
d, min and max must be of this type.
Parameters
d The value to clamp.
min The lower bound of the range.
max The upper bound of the range.
dissect_packet()
uint32_t gr::lora::dissect_packet (const void ** header, uint32_t header_size, const uint8_t * buffer, uint32_t offset) inline
hamming_decode_soft_byte()
static uint8_t gr::lora::hamming_decode_soft_byte (uint8_t v) inline static
Hamming(8,4) decoding by constructing a Syndrome matrix LUT for XORing on parity errors.
Parameters
v The byte to decode.
Returns
Returs a nibble containing the corrected data.
References bit(), and pack_nibble().
hamming_encode_soft()
uint8_t gr::lora::hamming_encode_soft (const uint8_t v) inline
Encode the given word with standard Hamming(7,4) and return a byte with the set parity bits.
Parameters
v The nibble to encode.
References bit(), and pack_byte().
pack_byte()
uint8_t gr::lora::pack_byte (const uint8_t a, const uint8_t b, const uint8_t c, const uint8_t d, const uint8_t e, const uint8_t f, const uint8_t g, const uint8_t h) inline
Pack the given 8 bits in a byte with: hgfe dcba
Parameters
a-h The bits to pack with the LSB first.
Referenced by hamming_encode_soft().
pack_nibble()
uint8_t gr::lora::pack_nibble (const uint8_t a, const uint8_t b, const uint8_t c, const uint8_t d) inline
Pack the given 4 bits in a nibble with: dcba
Parameters
a-d The bits to pack with the LSB first.
Referenced by hamming_decode_soft_byte().
print_interleave_matrix()
template<typename T > void gr::lora::print_interleave_matrix (std::ostream & out, const std::vector< T > & v, const uint32_t sf) inline
References to_bin().
print_vector()
template<typename T > void gr::lora::print_vector (std::ostream & out, const T * v, const std::string & prefix, const int size, const int element_len_bits) inline
References to_bin().
print_vector_bin()
template<typename T > void gr::lora::print_vector_bin (std::ostream & out, const std::vector< T > & v, const std::string & prefix, const int element_len_bits) inline
Append the data in a given vector to an output stream with a comma delimiter.
Template Parameters
T The type of variable to append.
Parameters
out The output stream to append to.
v The vector containing the data to append.
prefix A prefix to include before appending the data.
element_len_bits The length in bits of the data in v.
References to_bin().
print_vector_hex()
template<typename T > void gr::lora::print_vector_hex (std::ostream & out, const T * v, const uint32_t size, bool endline) inline
rotl()
uint32_t gr::lora::rotl (uint32_t bits, uint32_t count = 1u, const uint32_t size = 8u) inline
Rotate the given bits to the left and return the result.
Parameters
bits The value to rotate.
count The amount of bits to rotate (shift to left and add to right).
size The size in bits used in bits.
e.g. 1 byte given => size = 8
e.g. only 6 bits in use => size = 6, and all bits higher than (1 << size-1) will be zeroed.
select_bits()
uint32_t gr::lora::select_bits (const uint32_t data, const uint8_t * indices, const uint8_t n) inline
Select the bits in data given by the indices in *indices.
Parameters
data The data to select bits from.
*indices Array with the indices to select.
n The amount of indices.
to_bin()
template<typename T > std::string gr::lora::to_bin (const T v, const uint32_t bitwidth) inline
Return the v represented in a binary string.
Template Parameters
T The type of variable to convert.
Parameters
v The value to convert.
bitwidth The length in bits of the given variable v.
Referenced by print_interleave_matrix(), print_vector(), and print_vector_bin().
Variable Documentation
prng_header
const uint8_t gr::lora::prng_header[]
Initial value:
= {
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        }
Header whitening sequence
prng_payload
const uint8_t gr::lora::prng_payload[]
Initial value:
= {
            0xff, 0xff, 0x2d, 0xff, 0x78, 0xff, 0xe1, 0xff, 0x00, 0xff, 0xd2, 0x2d, 0x55, 0x78, 0x4b, 0xe1, 0x66, 0x00, 0x1e, 0xd2, 0xff, 0x55, 0x2d, 0x4b, 0x78, 0x66, 0xe1, 0x1e, 0xd2, 0xff, 0x87, 0x2d, 0xcc, 0x78, 0xaa, 0xe1, 0xb4, 0xd2, 0x99, 0x87, 0xe1, 0xcc, 0x00, 0xaa, 0x00, 0xb4, 0x00, 0x99, 0x00, 0xe1, 0xd2, 0x00, 0x55, 0x00, 0x99, 0x00, 0xe1, 0x00, 0xd2, 0xd2, 0x87, 0x55, 0x1e, 0x99, 0x2d, 0xe1, 0x78, 0xd2, 0xe1, 0x87, 0xd2, 0x1e, 0x55, 0x2d, 0x99, 0x78, 0x33, 0xe1, 0x55, 0xd2, 0x4b, 0x55, 0x66, 0x99, 0x1e, 0x33, 0x2d, 0x55, 0x78, 0x4b, 0xe1, 0x66, 0x00, 0x1e, 0x00, 0x2d, 0x00, 0x78, 0xd2, 0xe1, 0x87, 0x00, 0xcc, 0x00, 0x78, 0x00, 0x33, 0xd2, 0x55, 0x87, 0x99, 0xcc, 0x33, 0x78, 0x55, 0x33, 0x99, 0x55, 0x33, 0x99, 0x87, 0x33, 0xcc, 0x55, 0xaa, 0x99, 0x66, 0x33, 0x1e, 0x87, 0x2d, 0xcc, 0x78, 0xaa, 0x33, 0x66, 0x55, 0x1e, 0x99, 0x2d, 0xe1, 0x78, 0x00, 0x33, 0x00, 0x55, 0xd2, 0x99, 0x55, 0xe1, 0x4b, 0x00, 0xb4, 0x00, 0x4b, 0xd2, 0x66, 0x55, 0xcc, 0x4b, 0xaa, 0xb4, 0x66, 0x4b, 0xcc, 0x66, 0xaa, 0xcc, 0xb4, 0xaa, 0x4b, 0x66, 0x66, 0xcc, 0xcc, 0xaa, 0x78, 0xb4, 0x33, 0x4b, 0x55, 0x66, 0x4b, 0xcc, 0x66, 0x78, 0xcc, 0x33, 0x78, 0x55, 0xe1, 0x4b, 0x00, 0x66, 0xd2, 0xcc, 0x87, 0x78, 0x1e, 0xe1, 0xff, 0x00, 0xff, 0xd2, 0x2d, 0x87, 0xaa, 0x1e, 0x66, 0xff, 0xcc, 0xff, 0xaa, 0x2d, 0x66, 0xaa, 0x1e, 0x66, 0xff, 0xcc, 0x2d, 0xaa, 0xaa, 0x66, 0xb4, 0x1e, 0x4b, 0xff, 0x66, 0x2d, 0x1e, 0xaa, 0x2d, 0xb4, 0xaa, 0x4b, 0xb4, 0x66, 0x99, 0x1e, 0xe1, 0x2d, 0xd2, 0xaa, 0x55, 0xb4, 0x99, 0x99, 0xe1, 0xe1, 0x00, 0xd2, 0xd2, 0x55, 0x87, 0x99, 0xcc, 0xe1, 0xaa, 0x00, 0x66, 0xd2, 0xcc, 0x87, 0x78, 0xcc, 0xe1, 0xaa, 0xd2, 0x66, 0x87, 0xcc, 0x1e, 0x78, 0xff, 0xe1, 0x2d, 0xd2, 0x78, 0x87, 0x33, 0x1e, 0x87, 0xff, 0x1e, 0x2d, 0x2d, 0x78, 0x78, 0x33, 0x33, 0x87, 0x87, 0x1e, 0xcc, 0x2d, 0x78, 0x78, 0xe1, 0x33, 0xd2, 0x87, 0x55, 0xcc, 0x4b, 0x78, 0x66, 0xe1, 0xcc, 0xd2, 0xaa, 0x55, 0xb4, 0x4b, 0x99, 0x66, 0x33, 0xcc, 0x55, 0xaa, 0x99, 0xb4, 0xe1, 0x99, 0xd2, 0x33, 0x55, 0x55, 0x4b, 0x99, 0xb4, 0xe1, 0x99, 0xd2, 0x33, 0x55, 0x55, 0x4b, 0x4b, 0xb4, 0xb4, 0x99, 0x4b, 0x33, 0xb4, 0x55, 0x99, 0x4b, 0x33, 0xb4, 0x87, 0x4b, 0x1e, 0xb4, 0x2d, 0x99, 0xaa, 0x33, 0x66, 0xc7, 0x1e, 0x1e, 0x2d, 0x2d, 0xaa, 0xaa, 0x66, 0x66, 0xcc, 0x1e, 0x78, 0x2d, 0x33, 0xaa, 0x87, 0x66, 0x1e, 0xcc, 0xff, 0x78, 0x2d, 0x33, 0xaa, 0x87, 0x66, 0x1e, 0x1e, 0xff, 0xff, 0x2d, 0xff, 0xaa, 0xff, 0x66, 0x2d, 0x1e, 0xaa, 0xff, 0xb4, 0xff, 0x99, 0xff, 0x33, 0x2d, 0x87, 0xaa, 0xcc, 0xb4, 0x78, 0x99, 0x33, 0x33, 0x87, 0x87, 0xcc, 0xcc, 0xaa, 0x78, 0xb4, 0x33, 0x4b, 0x87, 0xb4, 0xcc, 0x99, 0xaa, 0xe1, 0xb4, 0xd2, 0x4b, 0x87, 0xb4, 0xcc, 0x99, 0x78, 0xe1, 0xe1, 0xd2, 0x00, 0x87, 0x00, 0xcc, 0xd2, 0x78, 0x87, 0xe1, 0x1e, 0x00, 0x2d, 0x00, 0xaa, 0xd2, 0xb4, 0x87, 0x4b, 0x1e, 0xb4, 0x2d, 0x4b, 0xaa, 0xb4, 0xb4, 0x4b, 0x4b, 0x66, 0xb4, 0x1e, 0x4b, 0xff, 0xb4, 0xff, 0x4b, 0x2d, 0x66, 0x78, 0x1e, 0x33, 0xff, 0x55, 0xff, 0x4b, 0x2d, 0xb4, 0x78, 0x99, 0x33, 0xe1, 0x55, 0x00, 0x4b, 0xd2, 0xb4, 0x55, 0x99, 0x99, 0xe1, 0x33, 0x00, 0x87, 0xd2, 0x1e, 0x55, 0xff, 0x99, 0xff, 0x33, 0xff, 0x87, 0xff, 0x1e, 0x00, 0x00, 0x00, 0x00, 0x87, 0xe1, 0xaa, 0xcc,
        }
Whitening sequence